Dataset:
  subj: 1
  batch_size: 1536
  data_type: train
  brain_type: left
  data_dir: /content
  csv_file_path: /content/Text_Data
  model_save_folder: ./Model_Save
  train_type: image

MLP_model:
  channels: 32
  patch_size: 2
  dim: 3072
  depth: 3

parameter:
  epoch: 25
  lr: 0.0005
  