Dataset:
  subj: 1
  batch_size: 32
  data_type: train
  data_dir: /export/c07/xzhan233/MRI
  csv_file_path: /export/c07/xzhan233/MRI/Text_Data

MLP_model:
  input_size: 768
  output_size: 19004
  hidden_size: 1024
  num_layers: 6

parameter:
  epoch: 100
  lr: 0.01